# https://docs.atuin.sh/configuration/config/
key_path = "~/.atuin-key"
keymap_mode="vim-normal"
auto_sync = true
workspaces = true
dialect = "uk"
history_filter = ["yt-dlp", "non-free_Linux_Distributions"]
common_subcommands = [
	"apt",
	"cargo",
	"cm",
	"composer",
	"dnf",
	"docker",
	"git",
	"go",
	"ip",
	"kubectl",
	"nix",
	"nmcli",
	"npm",
	"pecl",
	"pnpm",
	"dotnet",
	"podman",
	"port",
	"systemctl",
	"tmux",
	"yarn",
	"zellij",
	"chezmoi",
	"mt",
	"just",
	"make",
	"uv",
	"bun",
	"jrnl",
]
common_prefix = [
	"sudo",
	"host"
]
