git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  mainBranches:
    - main
    - master
    - staging
keybinding:
  commits:
    # When using lazygit inside of tmux with nvim binds the default binds to move commits up and down clash
    moveUpCommit: <f2>
    moveDownCommit: <f3>
  files:
    # Use the default editor for writing commit messages
    commitChanges: "" # disables the default inline commit on 'c'
    commitChangesWithEditor: "c" # maps 'c' to open the commit editor
customCommands:
  # verbose rename - opens editor to change commit message, which also shows file changes
  - key: R
    context: commits
    command: git commit --allow-empty --amend --no-verify --message
    subprocess: true
