[window]
title = "tmux btw"
decorations_theme_variant = "Dark"

[scrolling]
history = 65535
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0
# normal = { family = "MonaspiceNe NFM", style = "Regular" }
# bold = { family = "MonaspiceNe NFM", style = "Bold" }
# italic = { family = "MonaspiceNe NFM", style = "Italic" }
# bold_italic = { family = "MonaspiceNe NFM", style = "Bold Italic" }
# offset = { x = 0, y = 3 }
# normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
# bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
# italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }


# [terminal.shell]
# By default, create or attach to an existing tmux session `main` if it exists
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]

[colors]
selection = { background = "#4A4A4A", text = "#ffffff" }

[colors.search]
matches = { background = "#4A4A4A"}

[colors.normal]
black = "#050505"
red = "#AC8A8C"
green = "#8AAC8B"
yellow = "#ACA98A"
blue = "#8F8AAC"
magenta = "#AC8AAC"
cyan = "#8AABAC"
white = "#f0f0f0"

[colors.bright]
black = "#191919"
red = "#C49EA0"
green = "#9EC49F"
yellow = "#C4C19E"
blue = "#A39EC4"
magenta = "#C49EC4"
cyan = "#C49EC4"
white = "#fafafa"

